-- ART JOURNEYS — seed data (idempotent via ON CONFLICT on unique slugs)
-- Imagery: curated, verified Unsplash photographs (galleries, museums, artworks,
-- architecture, craft) — chosen to match each destination/journey/story theme.

INSERT INTO destinations (slug, name, country, city, hero_image, summary, body_md, lat, lng) VALUES
('venice', 'Venice', 'Italy', 'Venice',
 'https://images.unsplash.com/photo-1572947650440-e8a97ef053b2?auto=format&fit=crop&w=1600&q=80',
 'The lagoon city that turns water into architecture — and every other year, into the world''s contemporary art stage.',
 E'## Venice\n\nA city built on the impossible, Venice has been a meeting point of East and West for a thousand years. We move through it slowly: by water, on foot, through palazzi closed to the ordinary visitor.', 45.4408, 12.3155),
('kyoto', 'Kyoto', 'Japan', 'Kyoto',
 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&w=1600&q=80',
 'A thousand years of refinement preserved in wood, paper, indigo and clay — where craft is treated as a spiritual discipline.',
 E'## Kyoto\n\nKyoto holds Japan''s living craft traditions. We sit with the makers — the indigo dyer, the bamboo weaver, the ceramicist — in workshops that have run for generations.', 35.0116, 135.7681),
('florence', 'Florence', 'Italy', 'Florence',
 'https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?auto=format&fit=crop&w=1600&q=80',
 'The cradle of the Renaissance, read not as a museum but as a workshop where modern seeing was invented.',
 E'## Florence\n\nWe approach the Renaissance through the eyes of its makers — early mornings in the Uffizi, private access to restoration studios, and the fresco cycles most visitors never reach.', 43.7696, 11.2558),
('oaxaca', 'Oaxaca', 'Mexico', 'Oaxaca de Juárez',
 'https://images.unsplash.com/photo-1577720643272-265f09367456?auto=format&fit=crop&w=1600&q=80',
 'Indigenous textile, natural dye and clay traditions held in the valleys of southern Mexico.',
 E'## Oaxaca\n\nIn the Zapotec villages of the Oaxaca valley, weaving and natural dyeing are unbroken lineages. We learn the slow grammar of cochineal, indigo and the backstrap loom.', 17.0732, -96.7266),
('lisbon', 'Lisbon', 'Portugal', 'Lisbon',
 'https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=1600&q=80',
 'A city written in blue and white tile — five centuries of azulejo as public art.',
 E'## Lisbon\n\nLisbon wears its history in ceramic. We trace the azulejo from baroque church interiors to contemporary studios still firing tile by hand.', 38.7223, -9.1393),
('marrakech', 'Marrakech', 'Morocco', 'Marrakech',
 'https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=1600&q=80',
 'Earthen architecture, zellige geometry and the riad — a tradition of building toward the inner courtyard.',
 E'## Marrakech\n\nBehind the medina''s blank walls lie courtyards of astonishing geometry. We study zellige, tadelakt and the architecture of intimacy with the craftsmen who still build it.', 31.6295, -7.9811)
ON CONFLICT (slug) DO NOTHING;

INSERT INTO journeys (slug, title, subtitle, destination_id, duration_days, price_from, currency, hero_image, gallery, highlights, theme, body_md) VALUES
('venice-biennale-immersion', 'Reading the Biennale', 'Five days inside the world''s oldest art biennial',
 (SELECT id FROM destinations WHERE slug='venice'), 5, 6800, 'USD',
 'https://images.unsplash.com/photo-1572947650440-e8a97ef053b2?auto=format&fit=crop&w=1600&q=80',
 ARRAY['https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1531913764164-f85c52e6e654?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?auto=format&fit=crop&w=1200&q=80'],
 ARRAY['Curator-led walks through the Giardini and Arsenale','Private collateral-event openings','Conversation with a national pavilion artist'],
 ARRAY['biennale','art'],
 E'## The journey\n\nWe read the Biennale the way a curator does — by theme, by tension, by what each pavilion is arguing against. Mornings in the Giardini, afternoons in the Arsenale, evenings at openings only insiders know about.'),
('venice-glass-and-light', 'Glass and Light', 'Murano furnaces and the craft of Venetian glass',
 (SELECT id FROM destinations WHERE slug='venice'), 4, 5200, 'USD',
 'https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=1600&q=80',
 ARRAY['https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1574182245530-967d9b3831af?auto=format&fit=crop&w=1200&q=80'],
 ARRAY['Private furnace session with a maestro','Historic Murano archives','Lagoon light study by boat'],
 ARRAY['craft'],
 E'## The journey\n\nGlassmaking in Murano is a closed world. We open it — a maestro''s furnace, the archives of a centuries-old house, and the particular silver light of the lagoon that shaped the craft.'),
('kyoto-craft-masters', 'The Hands of Kyoto', 'Indigo, bamboo and clay with living masters',
 (SELECT id FROM destinations WHERE slug='kyoto'), 6, 7400, 'USD',
 'https://images.unsplash.com/photo-1525909002-1b05e0c869d8?auto=format&fit=crop&w=1600&q=80',
 ARRAY['https://images.unsplash.com/photo-1577720643272-265f09367456?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1551913902-c92207136625?auto=format&fit=crop&w=1200&q=80'],
 ARRAY['Indigo dyeing with a sixth-generation dyer','Bamboo weaving workshop','Tea bowl firing with a Raku ceramicist'],
 ARRAY['craft'],
 E'## The journey\n\nSix days in the workshops of Kyoto''s living masters. We do not watch — we sit, we attempt, we fail, and we begin to understand why a single indigo vat can take a lifetime to read.'),
('florence-renaissance-private', 'The Renaissance, Privately', 'The Uffizi and the studios behind it',
 (SELECT id FROM destinations WHERE slug='florence'), 5, 6900, 'USD',
 'https://images.unsplash.com/photo-1554907984-15263bfd63bd?auto=format&fit=crop&w=1600&q=80',
 ARRAY['https://images.unsplash.com/photo-1545989253-02cc26577f88?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1564399580075-5dfe19c205f3?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1574182245530-967d9b3831af?auto=format&fit=crop&w=1200&q=80'],
 ARRAY['Before-hours Uffizi access','Inside a fresco restoration studio','Vasari Corridor private walk'],
 ARRAY['art'],
 E'## The journey\n\nWe enter the Uffizi before the doors open, stand alone before the Botticellis, and then go where the public cannot: the restoration studios where the Renaissance is kept alive, brushstroke by brushstroke.'),
('oaxaca-textile-trails', 'Indigo and Time', 'Natural dye and the backstrap loom in the Zapotec valleys',
 (SELECT id FROM destinations WHERE slug='oaxaca'), 7, 5900, 'USD',
 'https://images.unsplash.com/photo-1577720643272-265f09367456?auto=format&fit=crop&w=1600&q=80',
 ARRAY['https://images.unsplash.com/photo-1525909002-1b05e0c869d8?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1200&q=80'],
 ARRAY['Cochineal and indigo dye sessions','Backstrap weaving with master weavers','Village markets off the tourist map'],
 ARRAY['craft'],
 E'## The journey\n\nIn the villages around Oaxaca, weaving is memory. We spend a week learning the colors of the land — cochineal red, wild indigo — and the patience the backstrap loom demands.'),
('lisbon-azulejo-routes', 'The Blue Grammar', 'Five centuries of Lisbon tile',
 (SELECT id FROM destinations WHERE slug='lisbon'), 4, 4200, 'USD',
 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=1600&q=80',
 ARRAY['https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?auto=format&fit=crop&w=1200&q=80'],
 ARRAY['National Tile Museum private tour','Working azulejo studio session','Hidden church interiors'],
 ARRAY['art','craft'],
 E'## The journey\n\nLisbon is a city you read in blue. We follow the azulejo from baroque excess to modernist restraint, ending in a studio where tiles are still painted and fired entirely by hand.'),
('marrakech-architecture-medina', 'Geometry of the Courtyard', 'Zellige, tadelakt and the riad',
 (SELECT id FROM destinations WHERE slug='marrakech'), 5, 5600, 'USD',
 'https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=1600&q=80',
 ARRAY['https://images.unsplash.com/photo-1572947650440-e8a97ef053b2?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1200&q=80'],
 ARRAY['Zellige cutting workshop','Private riad architecture tour','Tadelakt plaster demonstration'],
 ARRAY['architecture','craft'],
 E'## The journey\n\nMoroccan architecture turns inward. We study the mathematics of zellige, the silk of tadelakt plaster, and the riad''s quiet logic — building toward the courtyard, away from the street.'),
('kyoto-architecture-temples', 'Wood, Moss and Shadow', 'The architecture of the Kyoto temple',
 (SELECT id FROM destinations WHERE slug='kyoto'), 5, 6100, 'USD',
 'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&w=1600&q=80',
 ARRAY['https://images.unsplash.com/photo-1583001931096-959e9a1a6223?auto=format&fit=crop&w=1200&q=80','https://images.unsplash.com/photo-1551913902-c92207136625?auto=format&fit=crop&w=1200&q=80'],
 ARRAY['Dawn temple visits before opening','Garden design with a Zen gardener','Traditional carpentry workshop'],
 ARRAY['architecture'],
 E'## The journey\n\nKyoto''s temples are arguments about light, time and impermanence built in cedar and moss. We visit at dawn, study the joinery, and sit with the gardeners who tend the moss by hand.')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO stories (slug, title, excerpt, cover_image, author, published_at, body_md) VALUES
('reading-the-biennale', 'How to Read a Biennale', 'A contemporary art biennial is not a museum. It is an argument. Here is how to follow it.',
 'https://images.unsplash.com/photo-1518998053901-5348d3961a04?auto=format&fit=crop&w=1600&q=80', 'Elena Marchetti', now() - interval '5 days',
 E'## How to read a Biennale\n\nMost visitors treat the Venice Biennale as a checklist. The curators treat it as a thesis. The difference is everything.\n\nStart with the title. Every Biennale has one, and it is a provocation. Read the pavilions as responses — some earnest, some furious, some evasive.'),
('indigo-and-time-oaxaca', 'Indigo and Time', 'Why a single color in Oaxaca can take a lifetime to understand.',
 'https://images.unsplash.com/photo-1525909002-1b05e0c869d8?auto=format&fit=crop&w=1600&q=80', 'Mateo Ruiz', now() - interval '12 days',
 E'## Indigo and time\n\nIn the Zapotec valleys, indigo is not bought. It is grown, fermented, coaxed. The vat is alive; it has moods. A master dyer reads it the way a sommelier reads wine.'),
('the-blue-grammar-of-lisbon', 'The Blue Grammar of Lisbon', 'Five centuries of azulejo, read as a language the whole city speaks.',
 'https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=1600&q=80', 'Sofia Almeida', now() - interval '20 days',
 E'## The blue grammar of Lisbon\n\nLisbon is tiled the way other cities are painted. The azulejo is not decoration; it is structure, insulation, devotion and memory, fired into glaze.'),
('kyoto-hands', 'The Hands of Kyoto', 'What changes when you stop watching a craft and start failing at it.',
 'https://images.unsplash.com/photo-1551913902-c92207136625?auto=format&fit=crop&w=1600&q=80', 'Anna Whitfield', now() - interval '28 days',
 E'## The hands of Kyoto\n\nYou can photograph a master indigo dyer for hours and learn nothing. The lesson only begins when your own hands enter the vat and come out the wrong shade of blue.')
ON CONFLICT (slug) DO NOTHING;

INSERT INTO partners (name, logo_url, category, website) VALUES
('Fondazione Querini Stampalia', 'https://picsum.photos/seed/partner1/240/120?grayscale', 'Museum', 'https://www.querinistampalia.org'),
('Kyoto Crafts Council', 'https://picsum.photos/seed/partner2/240/120?grayscale', 'Craft Guild', 'https://example.org/kyoto-crafts'),
('Museo Textil de Oaxaca', 'https://picsum.photos/seed/partner3/240/120?grayscale', 'Museum', 'https://museotextildeoaxaca.org'),
('Museu Nacional do Azulejo', 'https://picsum.photos/seed/partner4/240/120?grayscale', 'Museum', 'https://www.museudoazulejo.gov.pt'),
('Opificio delle Pietre Dure', 'https://picsum.photos/seed/partner5/240/120?grayscale', 'Restoration Studio', 'https://example.org/opificio'),
('Maison de la Photographie Marrakech', 'https://picsum.photos/seed/partner6/240/120?grayscale', 'Gallery', 'https://maisondelaphotographie.ma')
ON CONFLICT DO NOTHING;
